### PR TITLE
update makevars for CGAL 6.0.1

### PR DESCRIPTION
**Pull request by ericdunipace**
Hi, the new version of the CGAL headers has a new flag to disable GMP. I have a suggested pull request so that I can push the new header files to CRAN. An alternative is to link GMP in your makevars, which may be undesirable.

### CODE REVIEW

**Comment by m-jahn** [comment]
Dear Eric, thanks for the heads-up and the work you put in RcppCGAL maintenance.
I will try to test and merge your PR. What consequences will this flag have? There's already a `NO-GMP` flag but now there are two somewhat equivalent flags? Regarding the time line of package submission: Will my package fail on CRAN as soon as you submit your new release with the breaking change?

**Comment by m-jahn** [comment]
I have checked your commit against the current and your new version of RcppCGAL and it builds (and works) without problems. You never know what's going to happen with CRAN's own package checks but I'm willing to take the risk and merge your PR.

**Comment by ericdunipace** [comment]
I think they just changed the flag for the 6.0 version of CGAL, as far as I can tell. Without it, your package didn't build on my machine with the new headers (unless I link GMP); with the flag, everything seems ok. Let me know if you run into problems though! Happy to try and trouble shoot as much as possible.

**Comment by ericdunipace** [comment]
FYI, I'm submitting the new version of RcppCGAL to CRAN, which will break the version of WeightedTreemaps there.

**Comment by m-jahn** [comment]
Thanks for letting me know, and go ahead!
I will submit my updated package soon after to CRAN, so this should work out fine.

**Pull request merged**
